mutation CreateUser(
  $firebaseUid: String!
  $nickname: String!
  $termsAgreedAt: Timestamp!
  $privacyAgreedAt: Timestamp!
  $emailMarketingAgreed: Boolean!
  $emailMarketingAgreedAt: Timestamp
) @auth(level: USER) {
  user_insert(
    data: {
      firebaseUid: $firebaseUid
      nickname: $nickname
      termsAgreedAt: $termsAgreedAt
      privacyAgreedAt: $privacyAgreedAt
      emailMarketingAgreed: $emailMarketingAgreed
      emailMarketingAgreedAt: $emailMarketingAgreedAt
    }
  )
}

mutation CreateStudyCompletion($verseId: Int!) @auth(level: USER) {
  studyCompletion_insert(data: { userId: $uid, verseId: $verseId })
}

mutation AddBookmark($verseId: Int!) @auth(level: USER) {
  bookmark_insert(data: { userId: $uid, verseId: $verseId })
}

mutation DeleteBookmark($verseId: Int!) @auth(level: USER) {
  bookmark_delete(key: { userId: $uid, verseId: $verseId })
}
