query GetVerse($id: Int!) @auth(level: USER) {
  verse(id: $id) {
    id
    number
    reference
    fullText
    words
    maskedStep2
    maskedStep3
    maskedStep4
  }
}

query GetMyCurrentVerse($userId: UUID!) @auth(level: USER) {
  studyCompletions(where: { userId: { eq: $userId } }, orderBy: { completedAt: DESC }, limit: 1) {
    verse {
      number
    }
  }
}

query GetMyBookmarks($userId: UUID!) @auth(level: USER) {
  bookmarks(where: { userId: { eq: $userId } }) {
    id
    verse {
      id
      number
      reference
      fullText
    }
    createdAt
  }
}

query GetMyCompletions($userId: UUID!) @auth(level: USER) {
  studyCompletions(where: { userId: { eq: $userId } }) {
    id
    verse {
      id
      number
      reference
    }
    completedAt
  }
}
